### ISSUE TITLE
ModuleNotFoundError: No module named 'core'

### ISSUE THREAD

**Issue by danieltanhx** [mhamilton723/STEGO#75]
i have tried to both Python 3.8.15 and python 3.6.9

src/eval_segmentation.py:57: UserWarning: 
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  @hydra.main(config_path="configs", config_name="eval_config.yml")
/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/plugins/config_source.py:126: UserWarning: Support for .yml files is deprecated. Use .yaml extension for Hydra config files
  "Support for .yml files is deprecated. Use .yaml extension for Hydra config files"
/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/_internal/hydra.py:127: UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
See https://hydra.cc/docs/1.2/upgrades/1.1_to_1.2/changes_to_job_working_dir/ for more information.
  configure_logging=with_log_configuration,
/usr/local/envs/stego3/lib/python3.6/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (UnsupervisedMetrics). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
                
  warnings.warn(*args, **kwargs)
Error executing job with overrides: []
Traceback (most recent call last):
  File "src/eval_segmentation.py", line 219, in <module>
    my_app()
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/main.py", line 99, in decorated_main
    config_name=config_name,
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/_internal/utils.py", line 401, in _run_hydra
    overrides=overrides,
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/_internal/utils.py", line 458, in _run_app
    lambda: hydra.run(
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    overrides=overrides,
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "src/eval_segmentation.py", line 72, in my_app
    picie_state = torch.load("/content/drive/MyDrive/saved_models/picie_and_probes.pth")
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/torch/serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/envs/stego3/lib/python3.6/site-packages/torch/serialization.py", line 853, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'core'

**Comment by KennyChen880127** [comment]
You should change True to False from eval_config.yml>>`run_picie: False`. I hope it will be helpful.

**Comment by gtq0801** [comment]
I met the same question, but I have no idea about the impact of the close of the run_picie.
